name: test

on:
  push:
    branches: [v2]
  pull_request:
    branches: [v2]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - run: yarn run test
      - run: yarn codecov
